seed: 3301
num_replicates: 50
population_size: 12
recomb_per_gen: 1
num_chroms: 1 # Chromosomes
runs_per_sample: 3    # Replicate runs per sample
coverage_cv: 0.3
genome_size: 1000000
mash: true
keep_reads: false
kwip: true
kwip_sketch_sizes:
  - "1e8"
  - "1e7"
mash_sketch_sizes:
  - 1000
  - 1000000

# Pairs of coverage, tree scale (i.e. $\pi$, mean pairwise dist.)
coverage_variablity:
  - {cov: 1, var: 0.01}
  - {cov: 2, var: 0.01}
  - {cov: 4, var: 0.01}
  - {cov: 8, var: 0.01}
  - {cov: 16, var: 0.01}
  - {cov: 32, var: 0.01}
  - {cov: 64, var: 0.01}
  - {cov: 128, var: 0.01}

#  - {cov: 16, var: 0.2}
#  - {cov: 16, var: 0.1}
#  - {cov: 16, var: 0.05}
#  - {cov: 16, var: 0.02}
#    #- {cov: 16, var: 0.01} It's above
#  - {cov: 16, var: 0.005}
#  - {cov: 16, var: 0.002}
#  - {cov: 16, var: 0.001}

  - {cov: 32, var: 0.2}
  - {cov: 32, var: 0.1}
  - {cov: 32, var: 0.05}
  - {cov: 32, var: 0.02}
    #- {cov: 32, var: 0.01} It's above
  - {cov: 32, var: 0.005}
  - {cov: 32, var: 0.002}
  - {cov: 32, var: 0.001}

  - {cov: 8, var: 0.2}
  - {cov: 8, var: 0.1}
  - {cov: 8, var: 0.05}
  - {cov: 8, var: 0.02}
    #- {cov: 8, var: 0.01} It's above
  - {cov: 8, var: 0.005}
  - {cov: 8, var: 0.002}
  - {cov: 8, var: 0.001}
