seed: 3301
num_replicates: 1
population_size: 6
recomb_per_gen: 1
num_chroms: 1 # Chromosomes
runs_per_sample: 2 # Replicate runs per sample
coverage_cv: 0.3
genome_size: 10000
sketch_sizes:
  - "5e5"

# Pairs of coverage, tree scale (i.e. $\pi$, mean pairwise dist.)
coverage_variablity:
  - {cov: 1, var: 0.001}
  - {cov: 4, var: 0.001}
  - {cov: 4, var: 0.01}
  - {cov: 4, var: 0.001}
